## Transform point in coordinate frame B to point in coordinate frame A

In [1]:
import numpy as np
import os

In [2]:
# Constants
from math import pi

In [3]:
# Known transformation b/w frames
translation_A2B = np.array([2.0, 0.0, 0.5])
ypr_A2B = np.array([-pi/2, 0.0, -pi/2])

In [5]:
from math import cos, sin

def ypr2quat(yaw, pitch, roll):
  cr = cos(roll * 0.5)
  sr = sin(roll * 0.5)
  cp = cos(pitch * 0.5)
  sp = sin(pitch * 0.5)
  cy = cos(yaw * 0.5)
  sy = sin(yaw * 0.5)

  qw = cr * cp * cy + sr * sp * sy
  qx = sr * cp * cy - cr * sp * sy
  qy = cr * sp * cy + sr * cp * sy
  qz = cr * cp * sy - sr * sp * cy

  return np.array([qw, qx, qy, qz])

In [6]:
def quat2rotation(qw, qx, qy, qz):
  r00 = 1 - 2*qy*qy - 2*qz*qz
  r01 = 2*qx*qy - 2*qz*qw
  r02 = 2*qx*qz + 2*qy*qw
  r10 = 2*qx*qy + 2*qz*qw
  r11 = 1 - 2*qx*qx - 2*qz*qz
  r12 = 2*qy*qz - 2*qx*qw
  r20 = 2*qx*qz - 2*qy*qw
  r21 = 2*qy*qz + 2*qx*qw
  r22 = 1 - 2*qx*qx - 2*qy*qy
  return np.array([[r00, r01, r02], [r10, r11, r12], [r20, r21, r22]])

In [7]:
rotation_A2B = quat2rotation(*ypr2quat(*ypr_A2B))
print(rotation_A2B)

[[ 2.22044605e-16  2.22044605e-16  1.00000000e+00]
 [-1.00000000e+00  0.00000000e+00  2.22044605e-16]
 [ 0.00000000e+00 -1.00000000e+00  2.22044605e-16]]


In [8]:
rotation_B2A = np.linalg.inv(rotation_A2B)
print(rotation_B2A)

[[ 2.22044605e-16 -1.00000000e+00  4.93038066e-32]
 [ 2.22044605e-16  4.93038066e-32 -1.00000000e+00]
 [ 1.00000000e+00  2.22044605e-16  2.22044605e-16]]


In [9]:
translation_B2A = -translation_A2B
print(translation_B2A)

[-2.  -0.  -0.5]


In [10]:
rt_mat = np.hstack((rotation_B2A, translation_B2A.reshape(-1, 1)))
print(rt_mat)

[[ 2.22044605e-16 -1.00000000e+00  4.93038066e-32 -2.00000000e+00]
 [ 2.22044605e-16  4.93038066e-32 -1.00000000e+00 -0.00000000e+00]
 [ 1.00000000e+00  2.22044605e-16  2.22044605e-16 -5.00000000e-01]]


In [13]:
rt_mat = np.vstack((rt_mat, np.array([0.0, 0.0, 0.0, 1.0])))
print(rt_mat)

[[ 2.22044605e-16 -1.00000000e+00  4.93038066e-32 -2.00000000e+00]
 [ 2.22044605e-16  4.93038066e-32 -1.00000000e+00 -0.00000000e+00]
 [ 1.00000000e+00  2.22044605e-16  2.22044605e-16 -5.00000000e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [18]:
point_B = np.array([1.0, 1.0, 0.0])

In [19]:
point_B = np.hstack((point_B, 1.0)).reshape(-1, 1)
print(point_B)

[[1.]
 [1.]
 [0.]
 [1.]]


In [21]:
point_A = np.dot(rt_mat, point_B)
print(point_A)

[[-3.00000000e+00]
 [ 2.22044605e-16]
 [ 5.00000000e-01]
 [ 1.00000000e+00]]
